name: mops test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dfx
        uses: dfinity/setup-dfx@main
      - name: Confirm successful installation
        run: dfx --version

      - name: Remove old Node.js versions
        run: |
          sudo rm -rf /opt/hostedtoolcache/node
          npm cache clean --force

      - name: Hapus Versi Lama Node.js & Cache
        run: |
          sudo rm -rf /opt/hostedtoolcache/node/22.*
          npm cache clean --force
          rm -rf ~/.npm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm ci
      - run: npm test

      - name: Install latest mops
        run: npm install -g ic-mops

      - name: Cek Versi Node.js & Mops
        run: |
          node --version
          npm list -g --depth=0
          mops --version

      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: install mops packages
        run: mops install

      - name: run tests
        run: mops test
