name: mops test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove old global npm packages
        run: rm -rf /opt/hostedtoolcache/node

      - name: Install latest mops
        run: npm install -g ic-mops

      - name: Setup Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install dfx
        uses: dfinity/setup-dfx@main
      - name: Confirm successful installation
        run: dfx --version
      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: install mops packages
        run: mops install

      - name: run tests
        run: mops test
